### ISSUE TITLE
code does not differentiate between identical blocks

### ISSUE THREAD

**Issue by WahPlus** [Ponali/scratch-3ds#4]
when you add multiple identical blocks and stack some blocks on one of them, if you drag any of the identical blocks the stack teleports to them.

https://github.com/Ponali/scratch-3ds/assets/162732679/23b3b587-f258-4267-bfaa-e19ae98cc804

**Comment by WahPlus** [comment]
could be that when i was adding the blocks i didnt move them so they all ended up overlapping and when i separated them the stack mightve gotten added to all their lists

**Comment by dtplsongithub** [comment]
one possible solution is when adding a block to a list of blocks check if its already in other lists. (i think thats how a list of blocks is stored)
when attempting to replicate this bug, i can confirm this is how you can cause it to appear

**Comment by Ponali** [comment]
this has been fixed in a recent commit.
https://github.com/Ponali/scratch-3ds/commit/0d7136152fb04de67b832ce6b63457ba61263734
